name: Prerelease

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on: [push, workflow_dispatch]

jobs:
  prerelease:
    name: Prerelease
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: init
        uses: actions/checkout@v4

      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: 16 #lts/*
          
      - name: Set up SSH for private repository
        if: startsWith(matrix.os, 'macOS')
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Set up SSH for Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          mkdir C:\Users\runneradmin\.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > C:\Users\runneradmin\.ssh\id_rsa
          # 设置权限：移除 BUILTIN\Users 用户组的权限，确保私钥仅对当前用户可访问
          icacls C:\Users\runneradmin\.ssh\id_rsa /inheritance:r /grant:r "Administrators:F"
          icacls C:\Users\runneradmin\.ssh\id_rsa /inheritance:r /grant:r "SYSTEM:F"
          icacls C:\Users\runneradmin\.ssh\id_rsa /remove "BUILTIN\Users"
          icacls C:\Users\runneradmin\.ssh\id_rsa /remove "Users"
          
          # 将 GitLab 主机添加到 known_hosts
          ssh-keyscan -H gitlab.integem.co >> C:\Users\runneradmin\.ssh\known_hosts

      - name: Start ssh-agent and add private key
        if: startsWith(matrix.os, 'windows')
        run: |
          Start-Service ssh-agent
          ssh-add C:\Users\runneradmin\.ssh\id_rsa
          ssh-add -l # 列出已添加的密钥，确保密钥成功加载
      - name: Test SSH connection
        if: startsWith(matrix.os, 'windows')
        run: ssh -T git@gitlab.integem.co

      - name: clone
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b dev ${{secrets.GIT_ADDRESS}} .
        shell: bash

      - name: install
        run: npm i --legacy-peer-deps --verbose

      - name: rmi:old
        run: npm run rmi:old

      - name: win
        if: startsWith(matrix.os, 'windows')
        run: npm run app:windows

      - name: mac
        if: startsWith(matrix.os, 'macOS')
        run: |
          npm run build:prod
          npm run mac:dmg
          npm run mac:mas

      - name: get package
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: version

      - name: Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.package.outputs.version}}-alpha
          name: v${{steps.package.outputs.version}}-alpha
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          append_body: true
          files: |
            release/*.exe
            release/*.blockmap
            release/latest.yml
            release/*.dmg
            release/*.zip
            release/latest-mac.yml
            release/mas-universal/*.pkg
