name: Prerelease

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on: [push, workflow_dispatch]

jobs:
  prerelease:
    name: Prerelease
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{matrix.os}}
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: init
        uses: actions/checkout@v4
        
      - name: Set up SSH for private repository
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: 16 #lts/*

      - name: clone
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b dev ${{secrets.GIT_ADDRESS}} .
        shell: bash

      - name: Clone igame repository
        run: git clone ${{ secrets.IGAME_GIT_ADDRESS }} ./igame

      - name: Modify package.json to point to local igame
        run: |
          sed -i 's|"igame": ".*"|"igame": "file:./igame"|' package.json


      
      - name: install
        run: npm i --legacy-peer-deps
      - name: rmi:old
        run: npm run rmi:old

      - name: win
        if: startsWith(matrix.os, 'windows')
        run: npm run app:windows

      - name: mac
        if: startsWith(matrix.os, 'macOS')
        run: |
          npm run build:prod
          npm run mac:dmg
          npm run mac:mas

      - name: get package
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: version

      - name: Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.package.outputs.version}}-alpha
          name: v${{steps.package.outputs.version}}-alpha
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          append_body: true
          files: |
            release/*.exe
            release/*.blockmap
            release/latest.yml
            release/*.dmg
            release/*.zip
            release/latest-mac.yml
            release/mas-universal/*.pkg
