name: Prerelease

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on: [push, workflow_dispatch]

jobs:
  prerelease:
    name: Prerelease
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: init
        uses: actions/checkout@v4

      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: 16 #lts/*
          
      - name: Create .ssh directory if it does not exist
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          if (-Not (Test-Path -Path "$env:USERPROFILE\.ssh")) {
            New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.ssh"
          }

      # 添加 SSH 私钥并设置权限
      - name: Add SSH key and set permissions
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 将 GitLab 添加到 known_hosts
      - name: Add GitLab to known_hosts
        if: startsWith(matrix.os, 'windows')
        run: ssh-keyscan -H gitlab.integem.co >> C:\Users\runneradmin\.ssh\known_hosts
          
      - name: Test SSH connection
        if: startsWith(matrix.os, 'windows')
        run: ssh -T git@gitlab.integem.co

      - name: clone
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b dev ${{secrets.GIT_ADDRESS}} .
        shell: bash

      - name: install
        run: npm i --legacy-peer-deps --verbose

      - name: rmi:old
        run: npm run rmi:old

      - name: win
        if: startsWith(matrix.os, 'windows')
        run: npm run app:windows

      - name: mac
        if: startsWith(matrix.os, 'macOS')
        run: |
          npm run build:prod
          npm run mac:dmg
          npm run mac:mas

      - name: get package
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: version

      - name: Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.package.outputs.version}}-alpha
          name: v${{steps.package.outputs.version}}-alpha
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          append_body: true
          files: |
            release/*.exe
            release/*.blockmap
            release/latest.yml
            release/*.dmg
            release/*.zip
            release/latest-mac.yml
            release/mas-universal/*.pkg
