name: Release

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on:
  workflow_dispatch:
    inputs:
      alphaVersion:
        description: "alpha version."
        required: true
      version:
        description: "release version."
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1

      - name: download
        id: package
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{inputs.alphaVersion}}
          fileName: "*"
          out-file-path: "release"

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{inputs.version}}
          name: ${{inputs.version}}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          append_body: true
          files: release/*
      
      # 安装 b2 CLI
      - name: Install b2 CLI
        run: |
          pip install b2

      # 授权 B2 账户
      - name: Authorize B2 Account
        run: |
          b2 authorize-account ${{ secrets.B2_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }}
      
      # 上传 .dmg 文件到 B2 指定路径
      - name: Upload .dmg to B2
        run: |
          b2 upload-file ${{ secrets.B2_BUCKET_NAME }} release/*.dmg "software/iPlayer Edu.dmg"

      # 上传 .exe 文件到 B2 指定路径
      - name: Upload .exe to B2
        run: |
          b2 upload-file ${{ secrets.B2_BUCKET_NAME }} release/*.exe "software/iPlayer Edu.exe"
